name: Build (no tests)

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show tree (debug paths)
        run: |
          pwd
          ls -la
          ls -la ToDoApplication || true
          ls -la ToDoApplication/TodoAPI || true

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'  # your project targets net9.0

      - name: Restore
        run: dotnet restore ToDoApplication/TodoAPI/TodoAPI.csproj

      - name: Build
        run: dotnet build ToDoApplication/TodoAPI/TodoAPI.csproj --configuration Release --no-restore

        # after the Build step
      - name: Publish (framework-dependent)
        working-directory: ToDoApplication/TodoAPI
        run: dotnet publish -c Release -o ../../artifacts/TodoAPI

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: todoapi-publish
          path: artifacts/TodoAPI/**
          if-no-files-found: error
          retention-days: 7
